### ISSUE TITLE
The LiveProvider support param 'code', how can i use this plugin with the param 'code'

### ISSUE THREAD

**Issue by taiyangzaitianshang** [dnbexperience/babel-plugin-react-live#7]
```jsx
<LiveProvider
            code={code}
            scope={components}
>
      <LiveError />
      <LivePreview /> 
      <LiveEditor />
</LiveProvider>
```
like code above, i cannot just set children with the content of code. i need to use param code. does this support ? 

Thank you anyhow!

**Comment by tujoworker** [comment]
Not at the moment. Where would your TypeScript code be placed?
Should "code" be JSX?

**Comment by taiyangzaitianshang** [comment]
> Not at the moment. Where would your TypeScript code be placed? Should "code" be JSX?

I'm very sorry, I misunderstood the usage scenario I encountered earlier. Now it's resolved.

Thank you
